import { DEFAULT_PARAMS, normalizePatch, type SynthParams } from "./params";

export interface FactoryPreset {
  readonly name: string;
  readonly description: string;
  readonly params: SynthParams;
}

const patch = (overrides: Partial<SynthParams>): SynthParams => normalizePatch({
  ...DEFAULT_PARAMS,
  ...overrides,
  autoRun: 0,
});

export const FACTORY_PRESETS: readonly FactoryPreset[] = [
  {
    name: "Init Andoracle",
    description: "A clear two-saw starting patch.",
    params: patch({}),
  },
  {
    name: "Rubber Bass",
    description: "Punchy Type II bass with a short filter contour.",
    params: patch({
      vco1Coarse: 32.7,
      vco2Coarse: 32.7,
      vco2Fine: -7,
      mixer2Level: 0.82,
      mixer3Level: 0.68,
      filterType: 2,
      filterCutoff: 640,
      filterResonance: 0.48,
      filterMod3Amount: 0.62,
      adsrAttack: 0.005,
      adsrDecay: 0.24,
      adsrSustain: 0.2,
      adsrRelease: 0.12,
      vcaEnvelopeAmount: 1,
      driveEnabled: 1,
      driveAmount: 2.8,
    }),
  },
  {
    name: "Sync Brass",
    description: "Hard-sync sweep with a bright ARP-style four-pole filter.",
    params: patch({
      vco2Sync: 1,
      vco2Coarse: 246.94,
      vco2Fm2Source: 1,
      vco2Fm2Amount: 0.14,
      mixer2Level: 0.22,
      mixer3Level: 0.9,
      mixer3Source: 0,
      filterType: 3,
      filterCutoff: 1850,
      filterResonance: 0.28,
      filterMod3Amount: 0.38,
      adsrAttack: 0.08,
      adsrDecay: 0.62,
      adsrSustain: 0.58,
      adsrRelease: 0.52,
    }),
  },
  {
    name: "Random Voltage",
    description: "Clocked pink-noise S/H animates pitch and cutoff.",
    params: patch({
      lfoRate: 4.8,
      shInput1Level: 0,
      shInput2Level: 0.82,
      shLag: 0.018,
      vco1Fm2Source: 0,
      vco1Fm2Amount: 0.08,
      vco2Fm2Source: 0,
      vco2Fm2Amount: 0.12,
      mixer1Level: 0.08,
      filterCutoff: 980,
      filterResonance: 0.56,
      filterMod2Source: 0,
      filterMod2Amount: 0.52,
      delayEnabled: 1,
      delayTime: 235,
      delayMix: 0.22,
    }),
  },
  {
    name: "Metallic XOR",
    description: "The Odyssey pulse-XOR ring source with a narrow band.",
    params: patch({
      vco1Coarse: 110,
      vco2Coarse: 164.81,
      vco1PulseWidth: 0.37,
      vco2PulseWidth: 0.21,
      mixer1Source: 1,
      mixer1Level: 0.78,
      mixer2Level: 0,
      mixer3Level: 0,
      filterType: 1,
      filterCutoff: 3400,
      filterResonance: 0.64,
      hpfCutoff: 420,
      adsrDecay: 1.1,
      adsrSustain: 0.16,
      adsrRelease: 1.7,
      delayEnabled: 1,
      delayTime: 410,
      delayFeedback: 0.46,
      delayMix: 0.31,
    }),
  },
  {
    name: "Auto Drone",
    description: "Hands-free evolving filter and stereo delay.",
    params: normalizePatch({
      ...DEFAULT_PARAMS,
      autoRun: 1,
      autoNote: 43,
      vco1Coarse: 32.7,
      vco2Coarse: 49,
      vco2Fine: 5,
      vco1PwmAmount: 0.58,
      vco2PwmAmount: 0.42,
      lfoRate: 0.31,
      filterCutoff: 720,
      filterResonance: 0.58,
      filterMod2Source: 1,
      filterMod2Amount: 0.44,
      vcaInitialGain: 0.18,
      vcaEnvelopeAmount: 0.68,
      arAttack: 1.2,
      arRelease: 3.1,
      vcaEnvelopeSource: 0,
      delayEnabled: 1,
      delayTime: 560,
      delayFeedback: 0.54,
      delayMix: 0.38,
      delayTone: 4400,
      delaySpread: 0.72,
    }),
  },
];

export const getFactoryPreset = (name: string): FactoryPreset | undefined =>
  FACTORY_PRESETS.find((preset) => preset.name === name);
